name: recipes

services:
  recipes:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: recipes
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf